openapi: 3.0.0
info:
  version: 1.0.0
  title: Linguagens API
  description: A simple API development in Imersion Java by Alura in 2022
servers:
  - url: http://localhost:8080
    description: Developer
paths:
  /linguagens:
    get:
      description: Returns a list of linguagens
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    urlImage:
                      type: string
                    ranking:
                      type: integer
    post:
      description: Save the new linguagem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object 
              properties:
                  name:
                    type: string
                  urlImage:
                    type: string
                  ranking:
                    type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  urlImage:
                    type: string
                  ranking:
                    type: integer
                    